hosts: local
become: true
tasks:
  -name: Install required comments
   apt:
    name:
        -git
        -maven
        -openjdk-17-jdk
    state: present
  -name: Clone maven repo
    git:
      repo: https://github.com/training-support/FST_JUnit_Project.git
      dest: ~/FST_JUnit_Project


  -name: Run Maven Tests
   command: mvn clean test
    args:
        chdir: ~/FST_JUnit_Project